export const ORDER_PENDING_LIST_REQUEST = "ORDER_PENDING_LIST_REQUEST";
export const ORDER_PENDING_LIST_SUCCESS = "ORDER_PENDING_LIST_SUCCESS";
export const ORDER_PENDING_LIST_FAIL = "ORDER_PENDING_LIST_FAIL";