# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '40 13 * * 0'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.0.0"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'pnpm'

#      - name: Install dependencies
#        run: pnpm install --frozen-lockfile

#      - name: Install just ESLint formatter
#        run: |
#          pnpm add -Dw eslint
          # pnpm add -Dw eslint-plugin-standard
          # pnpm add -Dw eslint-config-standard
          # pnpm add -Dw @typescript-eslint/parser
          # pnpm add -Dw eslint-config-react-app
          # pnpm add -Dw @microsoft/eslint-formatter-sarif@3.1.0
          # pnpm add -Dw eslint@^9.0.0 @eslint/js globals eslint-plugin-react eslint-plugin-react-hooks

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: >-
          pnpm lint .
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: false

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
